[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/calculadora-shopee/*"
  to = "/calculadora-shopee/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
